export const PERMISSIONS = [
  "course:read",
  "course:create",
  "course:update",
  "course:delete",
  "student:read",
  "student:create",
  "student:update",
  "student:block",
  "attendance:read",
  "attendance:write",
  "attendance:update",
  "payment:read",
  "payment:refund",
  "payment:write",
  "notification:create",
  "notification:broadcast",
  "admin:manage",
  "admission:read",
  "admission:write",
  "quiz:read",
  "quiz:write",
  "notes:write",
  "cms:write",
  "staff:write",
  "gallery:write",
  "job:write",
  "scholarship:write",
  "coupon:write",
  "live:write",
  "notice:write",
  "translation:write",
  "audit:read",
  "role:manage",
  "fee:write",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const ROLE_KEYS = ["SUPER_ADMIN", "ADMIN", "STAFF", "TEACHER"] as const;
export type RoleKey = (typeof ROLE_KEYS)[number];

export const ROLE_PERMISSIONS: Record<RoleKey, Permission[] | "*"> = {
  SUPER_ADMIN: "*",
  ADMIN: [...PERMISSIONS],
  STAFF: [
    "course:read",
    "student:read",
    "student:create",
    "student:update",
    "attendance:read",
    "attendance:write",
    "payment:read",
    "payment:write",
    "admission:read",
    "admission:write",
    "notice:write",
    "cms:write",
    "notification:create",
    "fee:write",
  ],
  TEACHER: [
    "course:read",
    "student:read",
    "attendance:read",
    "attendance:write",
    "attendance:update",
    "quiz:read",
    "quiz:write",
    "notes:write",
    "live:write",
    "notice:write",
  ],
};
